Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,15 +27,24 @@ jobs:
       - name: Run Flutter analyze
         id: analyze
         run: |
-          output=$(flutter analyze)
-          echo "::set-output name=analysis_result::$output"
+          output=$(flutter analyze) || echo "::set-output name=analysis_result::error"
+          if [[ $output != "No issues Found!" ]]; then
+            exit 1
+          else
+            echo "::set-output name=analysis_result::$output"
+          fi
 
+  comment_on_commit:
+    needs: analyze
+    runs-on: ubuntu-latest
+
+    steps:
       - name: Comment on lint result on commit
         uses: actions/github-script@v4
         with:
           github-token: ${{ secrets.TOKEN }}
           script: |
-            const output = `${{ steps.analyze.outputs.analysis_result }}`;
+            const output = `${{ needs.analyze.outputs.analysis_result }}`;
             const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
             const context = github.context;
             await octokit.rest.repos.createCommitComment({
